<a href="https://colab.research.google.com/github/napo178/Aibro-examples/blob/main/Gradient_Boosting_in_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# Import pandas
import pandas as pd
import numpy as np

In [27]:
# Upload 'bike_rentals.csv' to dataFrame
df_orders = pd.read_csv('featureclean.csv')

In [28]:
# Display first 5 rows
df_orders.head()

,Unnamed: 0,id,uuid,customer_id,created_at,updated_at,location_id,location_table_id,notes,status,...,sub_total,expires_at,delivery_fee,is_reported,report_message,order_time,time,days,difference,status_mapping
0,0,1,cl284a0i325880ns68dvwikcj,1,2022-04-20 21:58:46,2022-04-20 21:58:46,2,NaN,NaN,OPEN,...,2.5,2022-04-22 21:58:46,0,False,NaN,2 days 00:00:00,2,2,NaN,0
1,1,17,cl2aisstu05100ns633dz0kq9,5,2022-04-22 14:20:49,2022-04-22 14:21:15,3,NaN,NaN,PENDING,...,4.0,2022-04-24 14:20:49,0,False,NaN,3 days 16:22:03,2,2,NaN,1
2,2,2,cl285bu2m06680ns665i3oj8b,1,2022-04-20 22:28:10,2022-04-20 22:28:11,2,NaN,NaN,OPEN,...,5.0,2022-04-22 22:28:10,0,False,NaN,2 days 00:29:24,2,2,NaN,0
3,3,3,cl285c0af07700ns604mku8po,1,2022-04-20 22:28:18,2022-04-20 22:28:19,2,NaN,NaN,OPEN,...,2.5,2022-04-22 22:28:18,0,False,NaN,2 days 00:29:32,2,2,NaN,0
4,4,4,cl285uklv01100ns6yz430lx3,2,2022-04-20 22:42:45,2022-04-20 22:42:45,2,NaN,NaN,OPEN,...,2.5,2022-04-22 22:42:45,0,False,NaN,2 days 00:43:59,2,2,NaN,0

In [29]:
# Show  descriptive statistics
df_orders.describe()

,Unnamed: 0,id,customer_id,location_id,location_table_id,notes,total,order_number,sub_total,delivery_fee,report_message,time,days,difference,status_mapping
count,2324.000000,2324.000000,2324.000000,2324.000000,0.0,0.0,2324.000000,2.324000e+03,2324.000000,2324.0,0.0,2324.000000,2324.000000,0.0,2324.000000
mean,1161.500000,77.966867,9.335198,4.889845,NaN,NaN,10.936962,4.231079e+08,10.473623,0.0,NaN,1.993546,1.993546,NaN,0.703528
std,671.025335,44.734441,4.665195,1.535321,NaN,NaN,15.746617,7.730815e+06,14.815708,0.0,NaN,0.080097,0.080097,NaN,0.755160
min,0.000000,1.000000,1.000000,1.000000,NaN,NaN,1.570000,4.220145e+08,1.500000,0.0,NaN,1.000000,1.000000,NaN,0.000000
25%,580.750000,39.000000,5.000000,3.000000,NaN,NaN,3.500000,4.222464e+08,3.500000,0.0,NaN,2.000000,2.000000,NaN,0.000000
50%,1161.500000,78.000000,10.000000,6.000000,NaN,NaN,5.920000,4.225035e+08,5.920000,0.0,NaN,2.000000,2.000000,NaN,1.000000
75%,1742.250000,117.000000,15.000000,6.000000,NaN,NaN,10.500000,4.227397e+08,10.000000,0.0,NaN,2.000000,2.000000,NaN,1.000000
max,2323.000000,155.000000,16.000000,6.000000,NaN,NaN,112.440000,5.223295e+08,102.000000,0.0,NaN,2.000000,2.000000,NaN,2.000000

In [30]:
# Display df_orders info
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2324 entries, 0 to 2323
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2324 non-null   int64
 1   id                 2324 non-null   int64
 2   uuid               2324 non-null   object
 3   customer_id        2324 non-null   int64
 4   created_at         2324 non-null   object
 5   updated_at         2324 non-null   object
 6   location_id        2324 non-null   int64
 7   location_table_id  0 non-null      float64
 8   notes              0 non-null      float64
 9   status             2324 non-null   object
 10  total              2324 non-null   float64
 11  order_method       2324 non-null   object
 12  order_number       2324 non-null   int64
 13  sub_total          2324 non-null   float64
 14  expires_at         2324 non-null   object
 15  delivery_fee       2324 non-null   int64
 16  is_reported        2324 non-null   bool
 17  report_message     0 non-null      float64
 18  order_time         2324 non-null   object
 19  time               2324 non-null   int64
 20  days               2324 non-null   int64
 21  difference         0 non-null      float64
 22  status_mapping     2324 non-null   int64
dtypes: bool(1), float64(6), int64(9), object(7)
memory usage: 401.8+ KB

In [31]:
# Sum null values
df_orders.isna().sum().sum()

9296

In [32]:
# Show null value in df_bikes
df_orders[df_orders.isna().any(axis=1)]

,Unnamed: 0,id,uuid,customer_id,created_at,updated_at,location_id,location_table_id,notes,status,...,sub_total,expires_at,delivery_fee,is_reported,report_message,order_time,time,days,difference,status_mapping
0,0,1,cl284a0i325880ns68dvwikcj,1,2022-04-20 21:58:46,2022-04-20 21:58:46,2,NaN,NaN,OPEN,...,2.50,2022-04-22 21:58:46,0,False,NaN,2 days 00:00:00,2,2,NaN,0
1,1,17,cl2aisstu05100ns633dz0kq9,5,2022-04-22 14:20:49,2022-04-22 14:21:15,3,NaN,NaN,PENDING,...,4.00,2022-04-24 14:20:49,0,False,NaN,3 days 16:22:03,2,2,NaN,1
2,2,2,cl285bu2m06680ns665i3oj8b,1,2022-04-20 22:28:10,2022-04-20 22:28:11,2,NaN,NaN,OPEN,...,5.00,2022-04-22 22:28:10,0,False,NaN,2 days 00:29:24,2,2,NaN,0
3,3,3,cl285c0af07700ns604mku8po,1,2022-04-20 22:28:18,2022-04-20 22:28:19,2,NaN,NaN,OPEN,...,2.50,2022-04-22 22:28:18,0,False,NaN,2 days 00:29:32,2,2,NaN,0
4,4,4,cl285uklv01100ns6yz430lx3,2,2022-04-20 22:42:45,2022-04-20 22:42:45,2,NaN,NaN,OPEN,...,2.50,2022-04-22 22:42:45,0,False,NaN,2 days 00:43:59,2,2,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319,2319,151,cl2l1d8nr14860ns680ogg8i9,15,2022-04-29 22:58:18,2022-04-29 22:59:31,6,NaN,NaN,PENDING,...,11.34,2022-05-01 22:58:18,0,False,NaN,11 days 00:59:32,2,2,NaN,1
2320,2320,152,cl2l1hqnj17640ns6yzaid445,15,2022-04-29 23:01:48,2022-04-29 23:01:48,6,NaN,NaN,OPEN,...,3.50,2022-05-01 23:01:48,0,False,NaN,11 days 01:03:02,2,2,NaN,0
2321,2321,153,cl2l1j7ps18930ns6c8r9va2k,15,2022-04-29 23:02:56,2022-04-29 23:02:57,6,NaN,NaN,OPEN,...,3.90,2022-05-01 23:02:56,0,False,NaN,11 days 01:04:10,2,2,NaN,0
2322,2322,154,cl2l1nymj19840ns6h3oqthrd,16,2022-04-29 23:06:38,2022-04-29 23:07:46,6,NaN,NaN,PENDING,...,3.50,2022-05-01 23:06:38,0,False,NaN,11 days 01:07:52,2,2,NaN,1
2323,2323,155,cl2o3ad3v00850ns6gwnp805h,10,2022-05-02 02:15:21,2022-05-02 2:15:22,6,NaN,NaN,OPEN,...,10.00,2022-05-04 02:15:21,0,False,NaN,13 days 04:16:35,2,2,NaN,0

In [33]:
# Display rows 56 and 81
df_orders.iloc[[56, 81]]

,Unnamed: 0,id,uuid,customer_id,created_at,updated_at,location_id,location_table_id,notes,status,...,sub_total,expires_at,delivery_fee,is_reported,report_message,order_time,time,days,difference,status_mapping
56,56,55,cl2ghzrih23200ns6fmw9dfb9,9,2022-04-26 18:44:52,2022-04-26 18:45:04,6,NaN,NaN,PAYMENT_PENDING,...,3.5,2022-04-28 18:44:52,0,False,NaN,7 days 20:46:06,2,2,NaN,2
81,81,77,cl2hxjgac19480ns6demgj8he,10,2022-04-27 18:47:51,2022-04-27 18:52:09,6,NaN,NaN,PAYMENT_PENDING,...,20.0,2022-04-29 18:47:51,0,False,NaN,8 days 20:49:05,2,2,NaN,2

In [34]:
# Groupby status with median
df_orders.groupby(['status']).median()

,Unnamed: 0,id,customer_id,location_id,location_table_id,notes,total,order_number,sub_total,delivery_fee,is_reported,report_message,time,days,difference,status_mapping
status,,,,,,,,,,,,,,,,
OPEN,1170.0,85.0,7.0,5.0,NaN,NaN,6.62,422456075.0,6.000,0.0,0.0,NaN,2.0,2.0,NaN,0.0
PAYMENT_PENDING,1161.5,75.0,10.0,6.0,NaN,NaN,4.00,422504700.5,3.975,0.0,0.0,NaN,2.0,2.0,NaN,2.0
PENDING,1153.0,69.0,10.0,6.0,NaN,NaN,4.00,422562515.0,4.000,0.0,0.0,NaN,2.0,2.0,NaN,1.0

In [35]:
df_orders.columns

Index(['Unnamed: 0', 'id', 'uuid', 'customer_id', 'created_at', 'updated_at',
       'location_id', 'location_table_id', 'notes', 'status', 'total',
       'order_method', 'order_number', 'sub_total', 'expires_at',
       'delivery_fee', 'is_reported', 'report_message', 'order_time', 'time',
       'days', 'difference', 'status_mapping'],
      dtype='object')

In [36]:
df_orders.dtypes

Unnamed: 0             int64
id                     int64
uuid                  object
customer_id            int64
created_at            object
updated_at            object
location_id            int64
location_table_id    float64
notes                float64
status                object
total                float64
order_method          object
order_number           int64
sub_total            float64
expires_at            object
delivery_fee           int64
is_reported             bool
report_message       float64
order_time            object
time                   int64
days                   int64
difference           float64
status_mapping         int64
dtype: object

In [37]:
df_orders.isnull().sum()

Unnamed: 0              0
id                      0
uuid                    0
customer_id             0
created_at              0
updated_at              0
location_id             0
location_table_id    2324
notes                2324
status                  0
total                   0
order_method            0
order_number            0
sub_total               0
expires_at              0
delivery_fee            0
is_reported             0
report_message       2324
order_time              0
time                    0
days                    0
difference           2324
status_mapping          0
dtype: int64

In [64]:
import plotly.express as px
fig=px.scatter(df_orders, x='id', y='total', color='status')
fig.show()

fig=px.scatter(df_orders, x='id', y='sub_total', color='status')
fig.show()

In [58]:
df_orders.dropna(subset=['id','customer_id','location_id','total','delivery_fee','difference'])

Empty DataFrame
Columns: [Unnamed: 0, id, uuid, customer_id, created_at, updated_at, location_id, location_table_id, notes, status, total, order_method, order_number, sub_total, expires_at, delivery_fee, is_reported, report_message, order_time, time, days, difference, status_mapping]
Index: []

[0 rows x 23 columns]

In [39]:
df2=df_orders.to_csv('new.csv',index='false')

In [40]:
df=pd.read_csv('new.csv')

In [41]:
df_orders.isnull().sum()

Unnamed: 0              0
id                      0
uuid                    0
customer_id             0
created_at              0
updated_at              0
location_id             0
location_table_id    2324
notes                2324
status                  0
total                   0
order_method            0
order_number            0
sub_total               0
expires_at              0
delivery_fee            0
is_reported             0
report_message       2324
order_time              0
time                    0
days                    0
difference           2324
status_mapping          0
dtype: int64

In [44]:
df.dtypes

Unnamed: 0             int64
Unnamed: 0.1           int64
id                     int64
uuid                  object
customer_id            int64
created_at            object
updated_at            object
location_id            int64
location_table_id    float64
notes                float64
status                object
total                float64
order_method          object
order_number           int64
sub_total            float64
expires_at            object
delivery_fee           int64
is_reported             bool
report_message       float64
order_time            object
time                   int64
days                   int64
difference           float64
status_mapping         int64
dtype: object

In [45]:
df['time']=pd.to_numeric(df['time'])

In [46]:
df.dtypes

Unnamed: 0             int64
Unnamed: 0.1           int64
id                     int64
uuid                  object
customer_id            int64
created_at            object
updated_at            object
location_id            int64
location_table_id    float64
notes                float64
status                object
total                float64
order_method          object
order_number           int64
sub_total            float64
expires_at            object
delivery_fee           int64
is_reported             bool
report_message       float64
order_time            object
time                   int64
days                   int64
difference           float64
status_mapping         int64
dtype: object

In [47]:
# Split data into X and y 
# model 1

X = df_orders[['id','customer_id','location_id','total','delivery_fee']]
y = df_orders['time']

In [ ]:
#model 2

In [48]:
df = df.reset_index()

In [49]:
from sklearn.model_selection import train_test_split

# Import Linear Regression
from sklearn.linear_model import LinearRegression

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2)

In [ ]:
# Silence warnings
import warnings
warnings.filterwarnings('ignore')

In [51]:
# Import XGBRegressor
from xgboost import XGBRegressor

# Instantiate the XGBRegressor, xg_reg
xg_reg = XGBRegressor()

# Fit xg_reg to training set
xg_reg.fit(X_train, y_train)

# Predict labels of test set, y_pred
y_pred = xg_reg.predict(X_test)

# Compute the mean_squared_error, mse
mse = mean_squared_error(y_test, y_pred)

# Compute the root mean squared error, rmse
rmse = np.sqrt(mse)

# Display the root mean squared error
print("RMSE: %0.2f" % (rmse))

[16:59:52] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 0.00

In [52]:
# Import cross_val_score
from sklearn.model_selection import cross_val_score

# Instantiate Linear Regression
model = LinearRegression()

# Obtain scores of cross-validation using 10 splits and mean squared error
scores = cross_val_score(model, X, y, scoring='neg_mean_squared_error', cv=10)

# Take square root of the scores
rmse = np.sqrt(-scores)

# Display root mean squared error
print('Reg rmse:', np.round(rmse, 2))

# Display mean score
print('RMSE mean: %0.2f' % (rmse.mean()))

Reg rmse: [0.09 0.06 0.09 0.06 0.09 0.07 0.09 0.07 0.09 0.07]
RMSE mean: 0.08

In [53]:
# Instantiate XGBRegressor
model = XGBRegressor(objective="reg:squarederror")

# Obtain scores of cross-validation using 10 splits and mean squared error
scores = cross_val_score(model, X, y, scoring='neg_mean_squared_error', cv=10)

# Take square root of the scores
rmse = np.sqrt(-scores)

# Display root mean squared error
print('Reg rmse:', np.round(rmse, 2))

# Display mean score
print('RMSE mean: %0.2f' % (rmse.mean()))

Reg rmse: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
RMSE mean: 0.00

In [55]:
# model2

X = df_orders[['id','customer_id','location_id','total','time']]
y = df_orders['delivery_fee']

In [65]:
# Import XGBRegressor
from xgboost import XGBRegressor

# Instantiate the XGBRegressor, xg_reg
xg_reg = XGBRegressor()

# Fit xg_reg to training set
xg_reg.fit(X_train, y_train)

# Predict labels of test set, y_pred
y_pred = xg_reg.predict(X_test)

# Compute the mean_squared_error, mse
mse = mean_squared_error(y_test, y_pred)

# Compute the root mean squared error, rmse
rmse = np.sqrt(mse)

# Display the root mean squared error
print("RMSE: %0.2f" % (rmse))

# Import cross_val_score
from sklearn.model_selection import cross_val_score

# Instantiate Linear Regression
model = LinearRegression()

# Obtain scores of cross-validation using 10 splits and mean squared error
scores = cross_val_score(model, X, y, scoring='neg_mean_squared_error', cv=10)

# Take square root of the scores
rmse = np.sqrt(-scores)

# Display root mean squared error
print('Reg rmse:', np.round(rmse, 2))

# Display mean score
print('RMSE mean: %0.2f' % (rmse.mean()))

[18:10:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
RMSE: 0.00
Reg rmse: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
RMSE mean: 0.00